### PR TITLE
Make cholesky(Positive, A) differentiable

### PR DESCRIPTION
**Pull request by bvdmitri**
This PR implements automatic differentiation support with `ForwardDiff.jl` and `ReverseDiff.jl` for `cholesky(Positive, A)` function. 

#26

### CODE REVIEW

**Review by timholy — COMMENTED** [review]
The code changes are fine, but I'd argue that you should protect your investment by adding a differentiability test. You could make `ForwardDiff` a test dependency.

**Comment by bvdmitri** [comment]
Totally agree. Initially I didn't want to include new dependencies for the package. I've added few tests and new dependencies under `[extra]` section in `Project.toml`. I also changed `Test` dependency to be in `[extra]` section.

**Comment by timholy** [comment]
Wonderful, a very nice enhancement. Thanks so much!

**Comment by bvdmitri** [comment]
Thanks! Was glad to help!

**Pull request merged**
